### ISSUE TITLE
Pause functionality

### ISSUE THREAD

**Issue by msargen** [msargen/arithmancer#3]
* What button to press to pause:
  * esc and/or p
* Functionality:
  * Everything in the background (the game itself) is frozen as is
* How should it look? 
  * Blur the actual game and have a new panel come up in the middle of it
* What should be in the pause menu
  * Continue (resumes the game)
  * Settings (placeholder)
  * Save (placeholder)
  * Quit (returns to menu screen)

**Comment by Scheills** [comment]
#27
